### ISSUE TITLE
sanity-deploy from a fresh install fails to deploy/build properly

### ISSUE THREAD

**Issue by david-j-davis** [sanity-io/example-company-website-gatsby-sanity-combo#103]
**Describe the bug**
From a fresh clone of the project, and creating a new project, and deployment (sanity-deploy), the project fails to build properly, and the "Connection to Sanity.io" loading animation doesn't go away. In addition, Chrome dev tools reports a failed build. See screenshots.

**To Reproduce**
1. Clone the project
2. Change the project ID for a fresh deployment
3. `yarn run sanity-deploy`

**Expected behavior**
Deployment shouldn't fail

**Screenshots**
![loading-never-stops](https://user-images.githubusercontent.com/3498223/59142168-b3f38680-896e-11e9-8e46-75f4ff7b06da.png)
![Screen Shot 2019-06-07 at 9 54 22 PM](https://user-images.githubusercontent.com/3498223/59142176-d4234580-896e-11e9-901f-04931467454e.png)

**Desktop (please complete the following information):**
OS: OSX 10.14.5
Browser: Chrome
Version 74.0.3729
@sanity/cli 0.140.33 (up to date)
@sanity/base 0.140.33 (up to date)
@sanity/cli 0.140.33 (up to date)
@sanity/components 0.140.33 (up to date)
@sanity/core 0.140.32 (up to date)
@sanity/default-layout 0.140.33 (up to date)
@sanity/default-login 0.140.15 (up to date)
@sanity/desk-tool 0.140.33 (up to date)

**Comment by kmelve** [comment]
I have trouble reproducing this as well. 

Do you see any error if you try to run the studio locally? So either by running `yarn start` in the root folder, or `sanity start` in the `/studio` folder?

**Comment by david-j-davis** [comment]
Hi Knut, I have no trouble running this locally- it compiles/builds just
fine and can view the studio no problem. Only when I `sanity deploy` do I
see the issue.

**Comment by kmelve** [comment]
The `Unexpected token <` and the 1 position at least tells me that there's something weird going on with the javascript files. What do these files actually contain?

**Comment by david-j-davis** [comment]
Well, I've not modified any of the files that exist in the repo except for
updating the projectID in sanity.json, and it's peculiar that I cannot
deploy these same set of files without an error, and you can.
https://github.com/sanity-io/example-company-website-gatsby-sanity-combo/tree/master/studio

**Comment by kmelve** [comment]
Fully agree! Even if it might be some sort of edge case, that doesn't help you much. If you do a `sanity build` from the studio folder, can you confirm that the files in `studio/dist/static/js/app.bundle.js` and `studio/dist/static/js/vendor.bundle.js` are indeed minified JavaScript?

**Comment by david-j-davis** [comment]
Hi Knut, confirmed, `sanity build` in the studio folder produces minified
app and vendor bundles. On another note, I can at least confirm that a
fresh `sanity init` with the Blog example I can successfully deploy without
a build failure.

**Comment by kmelve** [comment]
That's good to hear. I'm still curious what may have happened with your deployed studio, however. Feel free to send me an [email](mailto:knut@sanity.io) with the studio URL and the team can take a closer look at it to figure out what may have happened.

For what it's worth: The portfolio starter on [sanity.io/create](https://www.sanity.io/create) is very similar to this one.

**Comment by kmelve** [comment]
We found the error. When preparing this starter to work with Zeit’s Now, I set the studio basepath to `/studio`. That doesn't work with our hosting. This is now fixed.
