### ISSUE TITLE
Unknown field '_rawBody' on type 'SanityDynamicPage'

### ISSUE THREAD

**Issue by cuddeford** [sanity-io/example-company-website-gatsby-sanity-combo#128]
I have duplicated the existing `post` schema and template to get createable dynamic pages from within Sanity. All works except the `_rawBody` field used in all the other pages. This field didn't get generated automatically after setting up the schema. `body` was created just fine, storing all the blocks in a nested array. But I am unable to query `_rawBody` to pass directly to `@sanity/block-content-to-react`, instead I have to query all the nested fields in the `body` field which doesn't seem scalable. This also causes the Figure block inside the body to get the asset id instead of the url which throws an error.

**Expected behavior**
I expected my new `dynamicPage` schema to behave exactly like the `post` schema from which it was duplicated, thus automatically generating the `_rawBody` field.

**Comment by kmelve** [comment]
Have you redeployed the GraphQL API after altering the schema? (`sanity graphql deploy`). You might have to run `gatsby clean` after having redeployed the GraphQL API as well. You have to redeploy because the source plugin uses the schema-definition to create the types inside of Gatsby.

**Comment by cuddeford** [comment]
Ah of course. After running `sanity graphql deploy` from the `studio` directory it solved the issue.
Thanks!

**Comment by cuddeford** [comment]
I'm having the same issue with a different schema now that I'm trying to deploy the project.

I have run `sanity graphql deploy` and `sanity deploy` from the studio folder and but my Netlify deployment is failing to build because it can't find a raw field.

I've been using `sanity graphql deploy` whenever I've made changes locally to the schemas and this has worked properly, but only locally.
