### ISSUE TITLE
Missing "Site settings"...

### ISSUE THREAD

**Issue by amcc** [sanity-io/example-company-website-gatsby-sanity-combo#225]
**Describe the bug**
On a new clone I have followed the readme instructions (and read/watched blog post).

I have added site and company info settings - these are marked as synced.
Restarting the server with npm start still doesn't remove this error:

Error: Missing "Site settings". Open the studio at http://localhost:3333 and add some content to "Site settings" and restart the development server.

It might or might not be relevant, but sanity is not deployed at this stage and the site and company settings are marked as 'draft'

**To Reproduce**
1. clone new site from this repo and follow these instructions:
````
git clone git@github.com:sanity-io/example-company-website-gatsby-sanity-combo.git
cd example-company-website-gatsby-sanity-combo
npm install

# Install or upgrade the Sanity CLI to
# make sure you are on v0.140.0 or higher
npm install -g @sanity/cli
# Set up Sanity.io account and project (≈ 45s)
npm run init
````

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14
 - chrome

I also have the following warnings:
warn The GraphQL query in the non-page component
example-company-website-gatsby-sanity-combo-frontend: "/Users/alistairmcclymont/Sites/amcc.io/am-sanity/web/src/templates/blog-post.js" will not be run.
warn The GraphQL query in the non-page component
example-company-website-gatsby-sanity-combo-frontend: "/Users/alistairmcclymont/Sites/amcc.io/am-sanity/web/src/templates/project.js" will not be run.
Exported queries are only executed for Page components. It's possible you're
example-company-website-gatsby-sanity-combo-frontend: trying to create pages in your gatsby-node.js and that's failing for some
example-company-website-gatsby-sanity-combo-frontend: reason.

example-company-website-gatsby-sanity-combo-frontend: 8 pages                                         example-company-website-gatsby-s
example-company-website-gatsby-sanity-combo-frontend: anity-combo-frontend
example-company-website-gatsby-sanity-combo-studio: webpack built f05639d508c83f40a57c in 19147ms
example-company-website-gatsby-sanity-combo-studio: Content Studio successfully compiled! Go to http://localhost:3333

**Comment by kmelve** [comment]
Have you tried either publishing the `siteSettings` document, or added a read token to the gatsby-source-sanity settings in `gatsby-config.js`. Another option is to remove the error catching in the frontend code: https://github.com/sanity-io/example-company-website-gatsby-sanity-combo/blob/master/web/src/pages/index.js#L113

**Comment by amcc** [comment]
Thanks for the reply @kmelve, I think the issue may be around publishing. In this starter there's no publish button, unlike the standard gatsby sanity starter. Is there a reason why this isn't there?

I can try the other things - but the lack of a publish button would seem to be the source of it perhaps.

**Comment by kmelve** [comment]
Ah, that's a known bug. I think we have a fix for it right around the corner. It's related to the `__experimental_actions` that's in the siteSettings. You can temporarily disable it, or wait for us to push the fix. Sorry for the troubles!

**Comment by fvieira** [comment]
Hi @kmelve, unfortunately disabling `__experimental_actions` doesn't seem to make the Publish button appear.
I'm trying to convince a client to use Sanity and wanted to use this repo as the source for a demo to let the client play with the CMS, but without the Publish button, the experience is broken...
Can you give me some hint as to what the problem is related to? Maybe I could find a way to work around it...

**Comment by fvieira** [comment]
Annnd it's fixed! :tada: 
I just had to run `sanity upgrade`. Apparently some versions in the `package.json` are outdated and no longer work (`@sanity/cli`, `@sanity/default-layout` and `@sanity/desk-tool`).

**Comment by kmelve** [comment]
Glad to hear! I'll update this repo then :)

**Comment by amcc** [comment]
running sanity upgrade give me this in the terminal: ✔ All Sanity modules are at latest versions

Though in the Studio i'm told i have 3 updates:

> Upgrades available
> This Studio is no longer up to date and can be upgraded.
> Module | Installed | Latest | Importance
> -- | -- | -- | --
> @sanity/cli | 0.142.2 | 0.146.0 | Low
> @sanity/default-layout | 0.142.10 | 0.146.3 | Low
> @sanity/desk-tool | 0.142.10 | 0.146.3 | Low
> To upgrade, run the Sanity CLI upgrade command in your project folder from a terminal.
> sanity upgrade

**Comment by alpual** [comment]
> running sanity upgrade give me this in the terminal: ✔ All Sanity modules are at latest versions
> 
> Though in the Studio i'm told i have 3 updates:
> 
> > Upgrades available
> > This Studio is no longer up to date and can be upgraded.
> > Module | Installed | Latest | Importance
> > -- | -- | -- | --
> > @sanity/cli | 0.142.2 | 0.146.0 | Low
> > @sanity/default-layout | 0.142.10 | 0.146.3 | Low
> > @sanity/desk-tool | 0.142.10 | 0.146.3 | Low
> > To upgrade, run the Sanity CLI upgrade command in your project folder from a terminal.
> > sanity upgrade
> 
> i'm not sure why this isn't upgrading as the package.json within the studio folder is like this:
> "@sanity/cli": "^0.142.2",
> "@sanity/default-layout": "^0.142.10",
> "@sanity/desk-tool": "^0.142.10",
> 
> shouldn't that update them when running sanity upgrade?
> 
> -- edit to this
> I manually added the changes you made to the repository and updated with npm - that did the trick

I think you need to cd into the studio folder and then run `sanity upgrade` command. At least, that worked for me.
