### ISSUE TITLE
"Site Settings", "Company Info", "Pages" not editable on first run

### ISSUE THREAD

**Issue by idea34** [sanity-io/example-company-website-gatsby-sanity-combo#251]
**Describe the bug**
Followed the setup instructions and everything works fine for People, Blog Posts etc but not not for the options listed. The form fields present as not editable. (Inspect shows the markup set to readonly) Not sure if this is expected behavior somehow and I am missing something?

**To Reproduce**
1. Install per instructions
2. Run studio
3. Click on "Site Settings" (same for other sections)
4. Attempt to edit

**Expected behavior**
On install, all content options are editable, since the site won't display without the data.

**Screenshots**
![Screen Shot 2019-12-21 at 6 56 40 AM](https://user-images.githubusercontent.com/849048/71307733-ab214a00-23c0-11ea-9367-3619a0cd8914.png)
![Screen Shot 2019-12-21 at 7 05 18 AM](https://user-images.githubusercontent.com/849048/71307734-ad83a400-23c0-11ea-8f46-07a503ba7807.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browsers tried: Chrome, Safari, Firefox
 - Version Latest

**Comment by idea34** [comment]
It's these lines in siteSettings.js: 
`liveEdit: false,
  __experimental_actions: ['update', 'publish' /* 'create', 'delete' */],`
... once commented out, works as expected.

**Comment by arkaydeus** [comment]
Yes, I can confirm once commenting out, it works. Bit annoying as basically following the default tutorial doesn't get past initial install.

**Comment by arkaydeus** [comment]
You also have to do the same with companyInfo.js

**Comment by kmelve** [comment]
Valid points! We'll adjust these and add a comment for how to disable the create actions once you have a document. Thanks for reporting!
