### ISSUE TITLE
I can't add pages from sanity

### ISSUE THREAD

**Issue by dsfrederic** [sanity-io/example-company-website-gatsby-sanity-combo#254]
I can't add pages from sanity. No error to be seen. 

FYI: I'm completely new to gatsby/sanity

**Comment by BenSeward** [comment]
This is likely to do with the page type being included within the hiddenTypes array.

Go to `/studio/schemas/deskStructure.js`
replace `const hiddenTypes = ['category', 'companyInfo', 'page', 'person', 'post', 'project', 'siteSettings']`

with `const hiddenTypes = ['category', 'companyInfo', 'person', 'post', 'project', 'siteSettings']`

**Comment by bzmillerboy** [comment]
One small type I found in @BenSeward very helpful response.

```
      S.listItem()
        .title('Pages')
        .schemaType('page')
        .child(S.documentTypeList('page')),  
```

Missing "." before "title".

**Comment by kmelve** [comment]
Seems like you figured this out? Feel free to join our [community](https://slack.sanity.io) if you need more help!
