### ISSUE TITLE
npm run now-deploy

### ISSUE THREAD

**Issue by americanethnography** [sanity-io/example-company-website-gatsby-sanity-combo#65]
**Describe the bug**
Following the instructions I get an error message when I try to `npm run now-deploy` (I get the same error if I deploy to Zeit via GitHub):

On Zeit the site fails to deploy and returns an error message in the log: 

```
Error: Build was unable to create the distDir: public.
Make sure you mentioned the correct dist directory: https://zeit.co/docs/v2/deployments/official-builders/static-build-now-static-build/#configuring-the-dist-directory
    at validateDistDir (/tmp/utils/build-module/node_modules/@now/static-build/index.js:16:11)
    at Object.exports.build (/tmp/utils/build-module/node_modules/@now/static-build/index.js:37:7)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Expected behavior**
No error when deploying to Zeit. 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by jameshowelldev** [comment]
I'm getting this exact same error.

**Comment by kmelve** [comment]
Hi! Thanks for reporting, and sorry for the long wait. I've now added a `now.json` that should work. We have also published [this guide](https://zeit.co/guides/deploying-sanity-studio-with-now/) with a walk-through on how to deploy the studio with Now.
